// The share card generated by src/app/opengraph-image.tsx. Pages that define
// their own `openGraph`/`twitter` objects replace the inherited ones entirely
// (Next.js merges metadata shallowly), so they must reference it explicitly.
const ALT = "Slatech Solutions — Web Design & Software Development in Lagos, Nigeria";

export const OG_IMAGES = [{ url: "/opengraph-image", width: 1200, height: 630, alt: ALT }];
export const TWITTER_IMAGES = [{ url: "/twitter-image", width: 1200, height: 630, alt: ALT }];
